.catalog:
  name: "deviceplatform"
  version: "v0.9.1"
  description: "设备平台"
  uuid: deviceplatform-0
  minimum_rancher_version: v0.51.0


tomcat:
  scale: 1
  start_on_create: true

lb:
  scale: 1
  start_on_create: true
  lb_config:
    certs: []
    port_rules:
    - priority: 1
      protocol: http
      service: tomcat
      source_port: 40010
      target_port: 8080
    - priority: 2
      protocol: http
      service: tomcat
      source_port: 48000
      target_port: 8000
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    initializing_timeout: 60000
    interval: 2000
    strategy: recreate
    reinitializing_timeout: 60000

mysql:
  scale: 1
  start_on_create: true
